// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyorpbzvjnasyaqbggcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5b3JwYnp2am5hc3lhcWJnZ2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODI4MjIsImV4cCI6MjA3NDY1ODgyMn0.WTG7UBwYkuSWPruJL_Uz0u5l6wYJolakzI780q13B_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});